### ISSUE TITLE
Exception: Error: Can't download Oculus Runtime. Status 404

### ISSUE THREAD

**Issue by pasotee** [facebookexperimental/oculus-debugger-vscode#4]
Hello everyone, I am trying to run the Oculus Debugger from Visual Studio Code for an Unreal Engine project and I am facing the following error:

```
Using existing installation id: [8ace3d00-dd0f-4d19-b428-40762c3d7de4]
Created a Pigeon Session ID: [a49f41d1-ac75-4653-8e5d-51fac296db5a]
Analytics: [oculus-vscode-debugger:activation] = {}
Telemetry is disabled via a setting, skipping
Activated the extension: Oculus Debugger
Using JDB location from settings: C:\Program Files\Android\jdk\microsoft_dist_openjdk_1.8.0.25\bin\jdb.exe
Using adb location from settings: C:\Microsoft\AndroidSDK\25\platform-tools\adb.exe
Created local process runner
Assuming local workspace
*******
 Create debug adapter with configuration:
Previous download directory exists, removing C:\Users\oalex\.oculus_debugger_runtime\lldb
Previous download directory exists, removing C:\Users\oalex\.oculus_debugger_runtime\debugcito
Exception: Error: Can't download Oculus Runtime. Status 404
Stack trace: {Error: Can't download Oculus Runtime. Status 404
	at c:\Users\oalex\.vscode\extensions\oculus.oculus-vscode-debugger-1.0.8\dist\extension.js:13:177002
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Ee._downloadWithProgress (c:\Users\oalex\.vscode\extensions\oculus.oculus-vscode-debugger-1.0.8\dist\extension.js:13:176918)
	at async Ee._downloadAndInstallWithProgress (c:\Users\oalex\.vscode\extensions\oculus.oculus-vscode-debugger-1.0.8\dist\extension.js:13:176658)}
About to delete the lockfile
```

I am using Oculus Debugger version `1.0.8` is this still supported? Also tried with `1.0.7` but with same result.
I am running Windows 11, Unreal Engine 4.26 from your fork and VS Code 1.63

**Comment by pasotee** [comment]
@mnovakovic do you have some insights in this regard? Are the links still viable?

**Comment by mnovakovic** [comment]
We’re working on a fix, thanks for bringing this to our attention!

**Comment by pasotee** [comment]
@mnovakovic thanks a lot, that's highly appreciated! Thanks for getting back to me!

**Comment by pasotee** [comment]
Any updates or ETAs on this one?
